"""Main entry point for backend-only test.

This script loads vessel/params.json (generated by export.ks) and runs
the 1-axis solver for quick backend validation.
"""



import os
import sys
import json
import argparse
import numpy as np

ROOT_DIR = os.path.dirname(os.path.abspath(__file__))
SRC_DIR = os.path.join(ROOT_DIR, "src")
if SRC_DIR not in sys.path:
    sys.path.insert(0, SRC_DIR)

PARAMS_PATH = os.path.join(ROOT_DIR, "src", "vessel", "params.json")

def main():

    # 명령행 인수로 목표값 입력받기
    parser = argparse.ArgumentParser(description="1축 로켓 최적화 솔버 실행")
    parser.add_argument('--target_time', type=float, default=120.0, help='목표 도달 시간(tf, 초) (default: 120)')
    parser.add_argument('--target_altitude', type=float, default=500.0, help='목표 고도(h_goal, m) (default: 500)')
    parser.add_argument('--time_weight', type=float, default=0.5, help='비용함수 시간 가중치(w, 0~1)')
    args = parser.parse_args()

    if not os.path.exists(PARAMS_PATH):
        print(f"[ERROR] {PARAMS_PATH} 파일이 존재하지 않습니다.\nKSP에서 export.ks를 실행해 params.json을 먼저 생성하세요.")
        return
    with open(PARAMS_PATH, "r") as f:
        params = json.load(f)


    print("[INFO] 1축 로켓 최적화 솔버 테스트 (casadi 기반)")
    if len(sys.argv) == 1:
        print(f"[INFO] (기본값 사용) 목표 시간(tf): {args.target_time}, 목표 고도(h_goal): {args.target_altitude}, 시간 가중치(w): {args.time_weight}")
    else:
        print(f"[INFO] (명령행 인수 사용) 목표 시간(tf): {args.target_time}, 목표 고도(h_goal): {args.target_altitude}, 시간 가중치(w): {args.time_weight}")

    # one_axis_solver로 임포트 경로 일치
    from control_tower.engine import one_axis_solver as axis_solver
    tf = args.target_time
    h_goal = args.target_altitude
    v_goal = getattr(args, 'target_velocity', 0.0) if hasattr(args, 'target_velocity') else 0.0
    result = axis_solver.solve_1axis_optimal(params, tf, h_goal, v_goal)

    throttle_min = float(np.min(result['throttle']))
    throttle_max = float(np.max(result['throttle']))
    print("=== Optimal Solver Result Summary ===")
    print(f"throttle range: [{throttle_min:.2f}, {throttle_max:.2f}]")
    print(f"final altitude: {result['altitude'][-1]:.2f} m")
    print(f"final velocity: {result['velocity'][-1]:.2f} m/s")
    print(f"final mass: {result['mass'][-1]:.2f} kg")
    print(f"fuel used: {result['mass'][0] - result['mass'][-1]:.2f} kg")
    print("=============================")

    # DearPyGui 그래프 출력
    try:
        axis_solver.plot_result_dearpygui(result)
    except Exception as e:
        print(f"[INFO] DearPyGui 시각화는 건너뜀: {e}")

if __name__ == "__main__":
    main()